config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/', to: 'lobby#show'
  post '/host', to: 'lobby#host'
  post '/join', to: 'lobby#join'
  get '/game', to: 'game#show', as: 'game'
  get '/player', to: 'game#player', as: 'player'
  post '/lock', to: 'game#lock'
  post '/start', to: 'game#start'
  patch '/assign/:id', to: 'game#assign', as: 'assign'
  patch '/update/:id', to: 'game#update', as: 'update'
  get '/roles', to: 'game#all_roles', as: 'all_roles'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :players
  validates :name, uniqueness: true
  def full_edition
    if edition == 'sects'
      return "Sects & Violets"
    elsif edition == 'trouble'
      return "Trouble Brewing"
    elsif edition == 'moon'
      return "Bad Moon Rising"
    end
    edition
  end
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :role, optional: true
  belongs_to :game

  def dead
    false
  end
end

app/models/role.rb
class Role < ApplicationRecord
  def linky_name
    name.gsub(' ', '_')
  end

  def image
    "tokens/#{linky_name}_Token.png"
  end

  def wiki_link
    if linky_name == 'Devils_Advocate'
      return "http://bloodontheclocktower.com/wiki/Devil's_Advocate"
    end
    "http://bloodontheclocktower.com/wiki/#{self.linky_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def show
    if cookies.encrypted[:game_id].nil?
      return redirect_to '/player'
    end
    unless @game = Game.find(cookies.encrypted[:game_id])
      return redirect_to '/', alert: "Your game not found"
    end
    @roles = Role.where(edition: @game.edition)
  end

  def all_roles
    if cookies.encrypted[:game_id].nil?
      return redirect_to '/', alert: "Wrong place"
    end
    unless @game = Game.find(cookies.encrypted[:game_id])
      return redirect_to '/', alert: "Something broke"
    end
    @roles = Role.where(edition: @game.edition)
  end

  def player
    if cookies.encrypted[:player_id].nil?
      return redirect_to '/', alert: "No game found"
    end
    @player = Player.find(cookies.encrypted[:player_id])
    @game = @player.game
    @roles = Role.where(edition: @game.edition)
  end

  def lock
    @game = Game.find(cookies.encrypted[:game_id])
    @game.phase = 'assignment'
    @game.save
    redirect_to @game
  end

  def start
    @game = Game.find(cookies.encrypted[:game_id])
    @game.players.each do |player|
      if player.role.nil?
        return redirect_to @game, alert: "All players need a role."
      end
    end
    @game.phase = 'active'
    @game.save
    redirect_to @game
  end

  def assign
    @player = Player.find(params[:id])
    @player.update(assign_player)
    respond_to do |format|
      if @player.save
        @roles = Role.where(edition: @player.game.edition)
        format.js
      else
        return redirect_to '/game', alert: "Role not assigned."
      end
    end
  end

  def update
    @player = Player.find(params[:id])
    @player.update(update_player)
    respond_to do |format|
      if @player.save
        @roles = Role.where(edition: @player.game.edition)
        format.js
      else
        return redirect_to '/game', alert: "Player update failed."
      end
    end
  end

  private
  def assign_player
    params.require(:player).permit(:role_id)
  end
  def update_player
    params.require(:player).permit(:role_id, :drunk, :dead, :poisoned, :misc1, :misc2, :notes)
  end

end

app/controllers/lobby_controller.rb
class LobbyController < ApplicationController
  def show
    @game = Game.new
  end

  def host
    @game = Game.new(game_params)
    @game.phase = 'joining'
    unless @game.save
      return redirect_to '/', alert: "Game not created."
    end
    cookies.encrypted[:game_id] = @game.id
    cookies.encrypted[:player_id] = nil
    redirect_to @game
  end

  def join
    @game = Game.find_by(name: params[:game])
    if @game.nil?
      return redirect_to '/', alert: "That game does not exist."
    end
    demon = if params.has_key?(:demon) then true else false end
    @player = Player.new(name: params[:name], game: @game, willing_demon: demon)
    @player.save!
    cookies.encrypted[:game_id] = nil
    cookies.encrypted[:player_id] = @player.id
    redirect_to @player
  end

  private
    def game_params
      params.require(:game).permit(:name, :edition)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/lobby_helper.rb
module LobbyHelper
end

app/views/game/_assign.html.erb
<div id="player_assign_form_<%= player.id %>">
<%= form_with model: player, url: assign_path(player.id) do |f| %>
  <%= f.label :name, player.name %>
  <% if player.role %>
  <%= f.label :role_name, player.role.name %>
  <% else %>
  <%= f.label :role_name, "[Needs Role]" %>
  <% end %>
  <%= f.collection_select :role_id, roles, :id, :name, {:selected => if player.role.nil? then nil else player.role.id end, :include_blank => true }%>
  <%= f.submit "Save" %>
<% end %>
<% if player.willing_demon %>
<span>[demon]</span>
<% end %>
</div>

app/views/game/_playerlist.html.erb
<table>
  <tr>
    <th>Done</th>
    <th>Name</th>
    <th>Role</th>
    <th>Ability</th>
  </tr>
  <% players.each do |player| %>
  <tr>
    <td><input type="checkbox" name="night_checkbox"></td>
    <td><%= player.name %></td>
    <td><%= player.role.name %></td>
    <td><%= player.role.description %></td>
  </tr>
  <% end %>
</table>
<button onclick="uncheck('night_checkbox');">Clear</button>
<%= javascript_tag do %>
  function uncheck(name){
    checkboxes = document.getElementsByName(name);
    for(var i=0, n=checkboxes.length;i<n;i++) {
      checkboxes[i].checked = false;
    }
  }
<% end %>

app/views/game/_roles.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Faction</th>
    <th>Ability</th>
  </tr>
  <% roles.each do |role| %>
  <tr>
    <td><%= link_to role.name, role.wiki_link, {target: '_'} %></td>
    <td><%= role.faction %></td>
    <td><%= role.description %></td>
  </tr>
  <% end %>
</table>

app/views/game/_update.html.erb
<tr id="player_update_row_<%= player.id %>">
<%= form_with model: player, url: update_path(player.id) do |f| %>
  <td><%= f.label :name, player.name %></td>
  <td><%= link_to player.role.name, player.role.wiki_link, {target: '_'} %></td>
  <td><%= f.check_box :dead %></td>
  <td><%= f.check_box :poisoned %></td>
  <td><%= f.check_box :drunk %></td>
  <td><%= f.check_box :misc1 %></td>
  <td><%= f.check_box :misc2 %></td>
  <td><%= f.collection_select :role_id, roles, :id, :name, {:selected => player.role.id }%></td>
  <td><%= f.text_area :notes %></td>
  <td><%= f.submit "Update" %></td>
  <td><%= player.role.description %></td>
<% end %>
</tr>

app/views/game/all_roles.html.erb
<% @roles.each do |role| %>
<%= image_tag role.image, size: '300' %>
<% end %>

app/views/game/assign.js.erb
document.getElementById("player_assign_form_<%= @player.id %>")
  .innerHTML = "<%= j (render :partial => 'game/assign',
                       :locals => {player: @player, roles: @roles}) %>";

app/views/game/player.html.erb
<% if @game.phase == 'joining' %>
<h1>Waiting on players</h1>
<% elsif @game.phase == 'assignment' %>
<h1>Waiting on role</h1>
<% elsif @game.phase == 'active' %>
<h1>Game active with <%= @game.players.count %> players.</h1>
<% end %>
<h2><%= @game.full_edition %></h2>
<% if @game.phase == 'active' %>
<button onmousedown="document.getElementById('player_role').style.display = 'inline'"
        onmouseup="document.getElementById('player_role').style.display = 'none'"
        ontouchstart="document.getElementById('player_role').style.display = 'inline'"
        ontouchend="document.getElementById('player_role').style.display = 'none'">
Press to show role
</button>
<div id="player_role" style="display:none">
  <%= @player.role.name %>
  <%= @player.role.faction %>
  <%= @player.role.description %>
  <%= image_tag @player.role.image, size: '300' %>
</div>
<% end %>
<%= render 'game/roles', roles: @roles %>
<%= image_tag 'player_count.png' %>

app/views/game/show.html.erb
<% if @game.phase == 'joining' %>
  <h1>Waiting for players</h1>
  <h2>Room name: [<%= @game.name %>]</h2>
  <p><%= @game.players.count %> have joined.</p>
  <ol>
    <% @game.players.each do |player| %>
    <li><%= player.name %> - <%= player.willing_demon %></li>
    <% end %>
  </ol>
  <%= button_to "Lock Game", :lock %>
<% end %>

<% if @game.phase == 'assignment' %>
  <h1>Assign Roles to <%= @game.players.count %> players</h1>
  <% @game.players.each do |player| %>
  <%= render 'game/assign', player: player, roles: @roles %>
  <% end %>
  <%= button_to "Start Game", :start %>
  <%= render 'game/roles', roles: @roles %>
  <%= image_tag 'player_count.png' %>
<% end %>

<% if @game.phase == 'active' %>
  <h1>Game is active</h1>
  <table>
  <tr>
    <th>Name</th>
    <th>Role</th>
    <th>Dead</th>
    <th>Poisoned</th>
    <th>Drunk</th>
    <th>Misc1</th>
    <th>Misc2</th>
    <th>Change Role</th>
    <th>Notes</th>
  </tr>
  <% @game.players.each do |player| %>
  <%= render 'game/update', player: player, roles: @roles %>
  <% end %>
  </table>

  <h3>Night</h3>
  <%= render 'game/playerlist',
    players: @game.players.select { |player| player.role.night } %>

  <h3>First Night</h3>
  <%= render 'game/playerlist',
    players: @game.players.select { |player| player.role.first_day } %>

  <%= link_to 'All Roles', :all_roles, {target: '_'} %>
  <%= render 'game/roles', roles: @roles %>
<% end %>

app/views/game/update.js.erb
document.getElementById("player_update_row_<%= @player.id %>")
  .innerHTML = "<%= j (render :partial => 'game/update',
                       :locals => {player: @player, roles: @roles}) %>";

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bloodc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/lobby/show.html.erb
<h1>Blood on the Clock App</h1>

<%= form_for @game, url: {action: "host"} do |f| %>
  <%= f.label :name, 'Game Name' %>
  <%= f.text_field :name %>
  <%= f.label :edition, 'Which edition' %>
  <%= f.select :edition, [['Trouble Brewing', 'trouble'], ['Sects & Violets', 'sects'], ['Bad Moon Rising', 'moon']] %>
  <%= f.submit "Host Game" %>
<% end %>
<%= form_tag controller: 'lobby', action: 'join', method: 'post' do %>
  <%= label_tag :name, "Your Name" %>
  <%= text_field_tag :name %>
  <%= label_tag :game, "Game Name" %>
  <%= text_field_tag :game %>
  <%= label_tag :demon, "Are you willing to be the demon?" %>
  <%= check_box_tag :demon %>
  <%= submit_tag "Join Game" %>
<% end %>
<%= link_to 'Rejoin a game in progress', :game %>